<?php 
class routerGenerator{
	public function createrouter($n){
		if(!is_numeric($n)){
			echo "Error:  Input should be an integer";exit;
		}
		$conn = $this->databaseConnection();

		for($i=1; $i<=$n; $i++){
			$result = $this->insertAutoGeneratedRouter($conn);
			echo $i." record inserted success.".PHP_EOL;
		}
		
	}

	public function databaseConnection(){
		$conn = new mysqli("localhost","root","root",'router_app');
		if ($conn -> connect_errno) {
		  echo "Failed to connect to MySQL: " . $conn -> connect_error;
		  exit();
		}
		return $conn;
	}

	public function insertAutoGeneratedRouter($conn){
		$sapid = bin2hex(random_bytes(9));
		$hostname = bin2hex(random_bytes(7));
		$loopback = long2ip(mt_rand());
		$mac_address = implode(':', str_split(substr(md5(mt_rand()), 0, 12), 2));

		$sql = "INSERT INTO routers (sapid, hostname, loopback, mac_address)
				VALUES ('".$sapid."', '".$hostname."','".$loopback."','".$mac_address."')";
	    $result = $conn->query($sql);
	    if(!$result){
	    	$this->insertAutoGeneratedRouter($conn);
	    }
	    return $result;

	}

}

$obj = new routerGenerator();
$obj->createrouter($argv[1]);

?>